stages:
  - gitleaks
  - kics
  - docker-build
  - snyk
  - docker-push

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  AWS_REGION: eu-west-3
  AWS_ACCOUNT: 
  ECR_REGISTRY: $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com
  ECR_REPOSITORY: meetup
  IMAGE_WITH_TAG: $ECR_REGISTRY/$ECR_REPOSITORY:latest

gitleaks-job:
  stage: gitleaks
  image:
    name: "zricethezav/gitleaks"
    entrypoint: [""]
  script:
    - gitleaks detect -v --report-path gitleaks-report.json -c gitleaks.toml
  artifacts:
    when: always
    paths:
      - gitleaks-report.json
    expire_in: 1 hour

kics-scan-job:
  stage: kics
  image:
    name: checkmarx/kics:latest
    entrypoint: [""]
  script:
    - kics scan --fail-on "high" --no-progress -p ${PWD} -o ${PWD} --report-formats html --output-name kics-results
  artifacts:
    name: kics-results.html
    paths:
      - kics-results.html
    expire_in: 1 hour
  allow_failure: true

# docker-build-job:
#   stage: docker-build
#   image:
#     name: docker:latest
#     entrypoint: [""]
#   services:
#     - name: docker:dind
#       alias: docker
#   script:

# snyk-scan-job:
#   stage: snyk
#   image:
#     name: snyk/snyk:docker-latest20
#     entrypoint: [""]
#   services:
#     - name: docker:dind
#       alias: docker

# snyk-pages-job:
#   stage: snyk
#   image:
#     name: node:latest
#     entrypoint: [""]

# docker-push-job:
#   stage: docker-push
#   image:
#     name: amazon/aws-cli
#     entrypoint: [""]
#   services:
#     - name: docker:dind
#       alias: docker
